image: gitpod/workspace-java-17
tasks:
  - name: Setup & Run
    
    command: |
      # 1. Start the PostgreSQL database server.
      pg_ctl -D $PGDATA -l postgresql.log start
      
      # 2. IMPORTANT: Wait for 5 seconds to give the database time to initialize.
      sleep 5
      
      # 3. Create our database (the '|| true' ignores errors if it already exists).
      createdb chat_db || true
      
      # 4. Set the database URL for our Spring Boot application.
      export SPRING_DATASOURCE_URL="jdbc:postgresql://localhost:5432/chat_db?user=gitpod"
      
      # 5. Finally, build and run the application.
      ./mvnw spring-boot:run
      # This section tells Gitpod which ports to expose.
ports:
  - port: 8080 
    onOpen: open-preview
  - port: 5432
    onOpen: ignore