# This file tells Render exactly how to build and deploy your services.
# It overrides the automatic detection.

services:
  # This is your Spring Boot application.
  - type: web
    name: real-time-chat-bot
    # This is the most important line! We are forcing Render to use the Java environment.
    runtime: java
    plan: free # Use the free instance type
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/chat-0.0.1-SNAPSHOT.jar"
    envVars:
      # These lines automatically connect your app to the database below.
      # You do not need to copy-paste the URLs or passwords anymore.
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: chat-database # Must match the database name below
          property: internalConnectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: chat-database
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: chat-database
          property: password

  # This is your PostgreSQL database.
  - type: psql
    name: chat-database
    plan: free # Use the free database plan
