# This file tells Render exactly how to build and deploy your services.
# It overrides the automatic detection.

# Defines all the web services to be deployed.
services:
  - type: web
    name: real-time-chat-bot
    runtime: java # Forcing the Java environment
    plan: free
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/chat-0.0.1-SNAPSHOT.jar"
    envVars:
      # These lines automatically connect your app to the database defined below.
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: chat-database # This name MUST match the database name below
          property: internalConnectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: chat-database
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: chat-database
          property: password

# Defines all the databases to be created.
databases:
  - name: chat-database
    plan: free

